project:
  type: book
  preview:
    port: 1111

# execute:
#   freeze: auto

website: 
  announcement: 
    content: "полезные ссылки на источники по Data Science и языку программирования R"
    icon: bookmarks
    dismissable: false
    position: below-navbar
    type: light

book:
  title: "Rесурсы"
  favicon: fav.png
  # https://make.orlybooks.com/
  cover-image: orly-book-cover.png
  sidebar:
      collapse-level: 1
  navbar:
    right:
      - icon: telegram
        href: https://t.me/naukaidannye
    background: "#2860a1"
    #collapse-below: lg
    logo: logo.jpeg
  page-footer: 
    left: '© {{< now year >}} &#10072; Е.Н. Матеров &#10072; {{< fa brands telegram >}} Telegram [Наука и данные](https://t.me/naukaidannye){.external target="_blank"}<script>document.getElementById(''year'').innerHTML= new Date().getFullYear();</script>'
    right: |
      <span class="faux-block">Создано на {{< iconify simple-icons:quarto >}} [Quarto](https://quarto.org/){.external target="_blank"} | [![Netlify Status](https://api.netlify.com/api/v1/badges/f156508f-393f-4ffe-adae-8ff4f7fcdc9a/deploy-status)](https://app.netlify.com/sites/quarto-book-working/deploys){.external target="_blank"}</span>

  date: today
  author: "Евгений Матеров"
  # toc-depth: 2
  # toc-title: Разделы
  chapters:
    - index.qmd
    - blogs.qmd
    - part: "Книги"
      chapters:
        - books/books-Hadley.qmd
        - books/books-russian.qmd
        - books/books-english.qmd
        - books/books-ML.qmd
        - books/books-geo.qmd
        - books/books-statistics.qmd
        - books/books-DL.qmd
        - books/books-time-series.qmd
        - books/books-texts.qmd
        - books/books-economics.qmd
    - courses.qmd
    - part: "Визуализации"
      chapters: 
        - dataviz/ggplot2.qmd
        - dataviz/palettes.qmd
    - part: "Челленджи и социальные проекты"
      chapters: 
        - chellendges/TidyTuesday.qmd
        - chellendges/30DayMapChallenge.qmd
        - chellendges/30DayChartChallenge.qmd
        - chellendges/DuboisChallenge.qmd
        - chellendges/AdventofCode.qmd
    - part: "Quarto"
      chapters: 
        - quarto/quarto-links.qmd
        - quarto/quarto-storytelling.qmd
    - part: "Наборы полезных ссылок"
      chapters: 
        - links/useful-links.qmd
        - links/rsearch.qmd
    - videoblogs.qmd
    - datasets.qmd
    - misc.qmd

format:
  html:
    theme: 
      light: [cosmo, theme_book.scss]
    number-sections: false

# filters:
#   - auto-dark

lang: ru

language:
  title-block-published: "Дата обновления"

